// RE-Skills Data — extracted from catalog/skills-index.yaml, LIST.md, and SKILL.md frontmatters
// GitHub base URL for linking to skill files
const GITHUB_BASE = "https://github.com/jdm4pku/RE-Skills/blob/main/";

const PHASES = [
  { id: "Foundation",       number: 1, description: "Establish business requirements and project context", color: "emerald" },
  { id: "Elicitation",      number: 2, description: "Gather requirements from stakeholders", color: "sky" },
  { id: "Analysis",         number: 3, description: "Analyze, model, and structure requirements", color: "violet" },
  { id: "Specification",    number: 4, description: "Document requirements formally", color: "rose" },
  { id: "Validation",       number: 5, description: "Verify requirements quality before baselining", color: "amber" },
  { id: "Prioritization",   number: 6, description: "Order requirements by importance", color: "orange" },
  { id: "Management",       number: 7, description: "Ongoing requirements change and status management", color: "teal" },
  { id: "Cross-Cutting",    number: 8, description: "Skills spanning the entire RE lifecycle", color: "slate" }
];

const SKILLS = [
  {
    id: "acceptance-criteria",
    name: "Acceptance Criteria",
    description: "Write testable acceptance criteria using Given/When/Then, checklist, and rule-based formats.",
    intent: "Create acceptance criteria that define the specific, testable conditions under which a requirement is considered satisfied. Covers three formats (Given/When/Then, checklist, rule-based), SMART criteria for requirements, and the separation between acceptance criteria (conditions) and acceptance tests (procedures). Use this to close the gap between \"what does this requirement mean?\" and \"how do we prove it works?\"",
    type: "component",
    phase: "Specification",
    bestFor: ["Defining done for user stories and requirements", "Creating testable conditions for functional and non-functional requirements", "Bridging the gap between requirements and test cases"],
    scenarios: ["Developers keep asking what 'done' means for this requirement", "I need to write acceptance criteria that QA can turn into test cases"],
    estimatedTime: "5-10 min per requirement",
    path: "skills/acceptance-criteria/SKILL.md"
  },
  {
    id: "agile-requirements-process",
    name: "Agile Requirements Process",
    description: "Orchestrate RE for agile projects with just-in-time elaboration and continuous validation.",
    intent: "Guide requirements engineers through requirements engineering in agile contexts -- from initial product vision through backlog seeding, iteration planning, just-in-time elaboration, and continuous validation via sprint reviews. This workflow adapts traditional RE techniques for agile delivery while preserving the core principles of elicitation, analysis, specification, and validation.",
    type: "workflow",
    phase: "Cross-Cutting",
    bestFor: ["Adapting requirements engineering practices for agile delivery", "Balancing just-in-time elaboration with sufficient up-front understanding", "Establishing the product owner role in requirements governance"],
    scenarios: ["We are adopting Scrum but our user stories are too vague for developers to implement", "We want agile delivery but our domain is complex -- how much RE do we do up front?", "Our product owner needs help managing the backlog as a requirements vehicle"],
    estimatedTime: "1-2 weeks initial setup; continuous thereafter",
    path: "skills/agile-requirements-process/SKILL.md"
  },
  {
    id: "analysis-advisor",
    name: "Analysis Advisor",
    description: "Select the right modeling techniques based on requirement type and system complexity.",
    intent: "Guide requirements engineers in selecting the most effective combination of analysis and modeling techniques for their specific system and team context. Asks adaptive questions about requirement type focus, system complexity, team modeling experience, and key concerns to recommend from use cases, user stories, process models, data models, state models, decision tables, and dialog maps.",
    type: "interactive",
    phase: "Analysis",
    bestFor: ["Choosing which visual models to create during requirements analysis", "Matching analysis techniques to system characteristics", "Building a balanced analysis approach for a new project"],
    scenarios: ["I am starting requirements analysis and need to know which modeling techniques to use", "Our team always writes use cases but our system has complex data and business logic -- are we missing something?", "We have limited analysis time. Which 2-3 techniques will give us the most value?"],
    estimatedTime: "10-15 min",
    path: "skills/analysis-advisor/SKILL.md"
  },
  {
    id: "business-rule",
    name: "Business Rule",
    description: "Document business rules as structured, traceable specifications separate from functional requirements.",
    intent: "Identify, classify, and document business rules that constrain or govern system behavior. Business rules exist independently of any software system -- they are organizational policies, regulations, mathematical formulas, and domain constraints that must be reflected in requirements.",
    type: "component",
    phase: "Foundation",
    bestFor: ["Capturing organizational policies that affect system behavior", "Documenting regulatory or compliance rules separately from features", "Creating a traceable catalog of calculations and constraints"],
    scenarios: ["Our pricing has complex discount rules based on volume, customer tier, and contract terms", "Regulatory rules change often and I need them separate from requirements so I can update without rewriting the whole SRS"],
    estimatedTime: "10-20 min per rule",
    path: "skills/business-rule/SKILL.md"
  },
  {
    id: "change-control-advisor",
    name: "Change Control Advisor",
    description: "Evaluate change requests with impact analysis and scope creep detection.",
    intent: "Guide requirements engineers through the change control process -- from initial change request through impact analysis, approval decision, and implementation tracking. Covers the Change Control Board (CCB) model, change request attributes, impact analysis techniques using traceability, and scope creep detection.",
    type: "interactive",
    phase: "Management",
    bestFor: ["Evaluating a proposed requirements change for impact and feasibility", "Setting up a change control process for a project", "Detecting and managing scope creep"],
    scenarios: ["A stakeholder wants to add a new feature mid-development. How do I evaluate the impact?", "We need a change control process. Help me set one up.", "Requirements keep changing and the project is slipping. How do I get control?"],
    estimatedTime: "15-30 min per change request",
    path: "skills/change-control-advisor/SKILL.md"
  },
  {
    id: "change-control-process",
    name: "Change Control Process",
    description: "Establish and operate a change control process with CCB governance.",
    intent: "Guide requirements engineers through establishing a Change Control Board (CCB), defining a change request lifecycle, receiving and classifying proposed changes, performing impact analysis, making disposition decisions, and verifying implemented changes. This workflow prevents uncontrolled scope creep while ensuring legitimate changes are evaluated fairly and implemented reliably.",
    type: "workflow",
    phase: "Management",
    bestFor: ["Establishing a change control board and governance structure", "Processing change requests from submission through verification", "Measuring and controlling requirements volatility"],
    scenarios: ["We baselined requirements but changes keep arriving with no process to evaluate them", "Scope creep is killing our schedule but stakeholders say every change is critical", "I need to set up a CCB for a new project"],
    estimatedTime: "4-8 hours initial setup; 1-2 hours per change request",
    path: "skills/change-control-process/SKILL.md"
  },
  {
    id: "change-impact-analysis",
    name: "Change Impact Analysis",
    description: "Assess implications, affected work products, and effort for a proposed change.",
    intent: "Guide requirements engineers through a structured three-step impact analysis for proposed requirements changes. Covers the implications checklist, identification of all affected work products, and estimation of schedule and cost impact. Includes the 18 standard change request attributes from Wiegers.",
    type: "component",
    phase: "Management",
    bestFor: ["Assessing the full impact of a proposed change before committing to it", "Preparing change request packages for the change control board", "Identifying all work products affected by a requirements change"],
    scenarios: ["A stakeholder wants to add a new feature mid-sprint -- I need to assess the ripple effects", "The change control board needs a formal impact analysis before approving a change request", "A regulatory change affects our requirements -- I need to know what else it touches"],
    estimatedTime: "30-60 min per change request",
    path: "skills/change-impact-analysis/SKILL.md"
  },
  {
    id: "context-diagram",
    name: "Context Diagram",
    description: "Define system boundaries with external entities and data flows.",
    intent: "Create context diagrams that show the system as a single process with all external entities (users, systems, devices) and the data flows between them. Use this to establish a clear system boundary, identify all external interfaces that need requirements, and provide a visual scope definition that stakeholders can review quickly.",
    type: "component",
    phase: "Foundation",
    bestFor: ["Defining system boundaries and external interfaces", "Identifying all data flows into and out of the system", "Visual scope definition for stakeholder alignment"],
    scenarios: ["I need to show stakeholders exactly what is inside and outside the system boundary", "We keep discovering new interfaces mid-project -- I need a complete picture up front"],
    estimatedTime: "30-45 min",
    path: "skills/context-diagram/SKILL.md"
  },
  {
    id: "data-dictionary",
    name: "Data Dictionary",
    description: "Define data elements and structures using formal notation and CRUD analysis.",
    intent: "Create a structured data dictionary that formally defines every data element referenced in requirements, including primitive types, composite structures, repeating groups, and valid values. Includes CRUD matrix analysis for completeness checking.",
    type: "component",
    phase: "Specification",
    bestFor: ["Defining data elements referenced in requirements", "Detecting missing requirements through data flow analysis", "Eliminating ambiguity about data item meanings and formats"],
    scenarios: ["Requirements mention 'customer record' but nobody has defined what fields it contains", "I need to verify we have requirements for creating, reading, updating, and deleting every data entity"],
    estimatedTime: "30-60 min",
    path: "skills/data-dictionary/SKILL.md"
  },
  {
    id: "data-modeling",
    name: "Data Modeling",
    description: "Create entity-relationship diagrams for data entities, attributes, and relationships.",
    intent: "Build entity-relationship diagrams that identify the key data entities in a system, define their attributes, and specify the relationships (including cardinality and participation constraints) between them. Connects to the data dictionary for detailed attribute definitions.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Visualizing data entities and their relationships from requirements", "Discovering missing requirements through data structure analysis", "Communicating data architecture to developers and stakeholders"],
    scenarios: ["Requirements mention several data objects but nobody has mapped how they relate to each other", "I need to verify that use cases account for all entity relationships and constraints", "The development team needs a conceptual data model before designing the database"],
    estimatedTime: "45-90 min",
    path: "skills/data-modeling/SKILL.md"
  },
  {
    id: "decision-table",
    name: "Decision Table",
    description: "Specify complex combinatorial business logic with decision tables and trees.",
    intent: "Express complex business logic as decision tables (conditions x actions matrix) or decision trees (branching visual format). Use this when requirements involve multiple interacting conditions that determine different system behaviors.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Specifying complex business rules with multiple interacting conditions", "Detecting missing or contradictory requirements in combinatorial logic", "Converting ambiguous prose requirements into precise, testable specifications"],
    scenarios: ["The pricing logic has 5 conditions that interact, and the prose requirement is confusing everyone", "I need to make sure every possible combination of conditions has a defined system behavior"],
    estimatedTime: "15-30 min per table",
    path: "skills/decision-table/SKILL.md"
  },
  {
    id: "dialog-map",
    name: "Dialog Map",
    description: "Model user-system navigation flows, screen inventories, and transition rules.",
    intent: "Build dialog maps that model the navigation paths users follow through a system's user interface. Use this to create a screen inventory, define transition rules between screens, and discover missing UI requirements by systematically mapping every navigation path.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Modeling user interface navigation flows and screen transitions", "Discovering missing UI requirements through navigation analysis", "Creating a screen inventory linked to use cases"],
    scenarios: ["Requirements describe what users do but not how they navigate between screens", "I need to ensure every use case step has a corresponding screen and every screen is reachable", "The UI team needs a navigation specification before designing wireframes"],
    estimatedTime: "30-60 min",
    path: "skills/dialog-map/SKILL.md"
  },
  {
    id: "elicitation-interview",
    name: "Elicitation Interview",
    description: "Plan and conduct stakeholder interviews using structured question progressions.",
    intent: "Plan and conduct requirements elicitation interviews that move from broad context questions to specific behavioral questions, using active listening and past-behavior techniques to uncover real needs rather than hypothetical wishes.",
    type: "component",
    phase: "Elicitation",
    bestFor: ["Eliciting requirements from stakeholders through structured conversation", "Uncovering unstated needs and assumptions through targeted questioning", "Building rapport with domain experts while gathering precise requirements"],
    scenarios: ["I need to interview the lab manager about their chemical inventory needs but do not know where to start", "My stakeholder interviews keep producing vague wish lists instead of concrete requirements", "I want a reusable interview guide template for requirements elicitation"],
    estimatedTime: "30-60 min preparation, 45-90 min per interview",
    path: "skills/elicitation-interview/SKILL.md"
  },
  {
    id: "elicitation-technique-selector",
    name: "Elicitation Technique Selector",
    description: "Choose the right elicitation technique based on project context and constraints.",
    intent: "Guide requirements engineers in selecting the most effective elicitation technique(s) for their specific situation by asking adaptive questions about stakeholder access, type of information needed, project constraints, and organizational culture.",
    type: "interactive",
    phase: "Elicitation",
    bestFor: ["Choosing elicitation techniques for a new project or phase", "Deciding between interviews, workshops, and observation", "Adapting elicitation approach to stakeholder constraints"],
    scenarios: ["I have limited access to users (only 3 hours total) and need to maximize what I learn", "Help me decide whether to run a workshop or do individual interviews for this project", "Users can't articulate what they need -- what elicitation technique should I use?"],
    estimatedTime: "10-15 min",
    path: "skills/elicitation-technique-selector/SKILL.md"
  },
  {
    id: "moscow-prioritization",
    name: "MoSCoW Prioritization",
    description: "Categorize requirements into Must/Should/Could/Won't with allocation guidelines.",
    intent: "Guide requirements engineers through the MoSCoW prioritization method to categorize requirements into four distinct buckets with clear definitions and allocation guidelines. Includes the 60/20/20 allocation rule.",
    type: "component",
    phase: "Prioritization",
    bestFor: ["Timeboxed delivery where scope must be fixed to a timebox", "Getting stakeholder consensus on what is in vs. out for a release", "Agile release planning where simplicity and speed are valued over precision"],
    scenarios: ["We have a fixed deadline and need stakeholders to agree on minimum viable scope", "The product owner wants a quick categorization of 20 backlog items for the next sprint", "Stakeholders keep adding requirements -- I need a framework to push back on scope creep"],
    estimatedTime: "30-45 min",
    path: "skills/moscow-prioritization/SKILL.md"
  },
  {
    id: "observation-analysis",
    name: "Observation Analysis",
    description: "Discover unstated requirements by watching users work in their environment.",
    intent: "Plan and conduct observation sessions (job shadowing) that reveal unstated requirements, workarounds, and workflow inefficiencies that users cannot or will not articulate in interviews.",
    type: "component",
    phase: "Elicitation",
    bestFor: ["Discovering unstated requirements and tacit workflow knowledge", "Identifying workarounds that indicate gaps in the current process", "Understanding the real work environment and physical constraints"],
    scenarios: ["Stakeholders say the current process works fine, but error rates are high -- I need to see what is really happening", "I need to understand a lab workflow before the team can design the chemical inventory system", "Interview data does not match the defect data -- I need to observe the actual process"],
    estimatedTime: "30 min prep, 1-4 hours per session",
    path: "skills/observation-analysis/SKILL.md"
  },
  {
    id: "prioritization-advisor-re",
    name: "Prioritization Advisor",
    description: "Select a prioritization method -- MoSCoW, value/cost/risk, pairwise, $100, or others.",
    intent: "Guide requirements engineers in selecting and applying the right prioritization technique for their specific context. Covers in/out sorting, three-level scales, MoSCoW, pairwise comparison, $100 allocation, and value/cost/risk spreadsheets.",
    type: "interactive",
    phase: "Prioritization",
    bestFor: ["Choosing a prioritization method for a project", "Breaking deadlocks when stakeholders disagree on priority", "Moving beyond 'everything is high priority' to real trade-offs"],
    scenarios: ["We have 80 requirements and every stakeholder says theirs are all high priority", "Help me choose between MoSCoW and a scoring approach for prioritizing our backlog", "I need a quick prioritization method for 15 requirements with 3 stakeholders"],
    estimatedTime: "10-15 min",
    path: "skills/prioritization-advisor-re/SKILL.md"
  },
  {
    id: "process-modeling",
    name: "Process Modeling",
    description: "Create activity diagrams and swim-lane diagrams for cross-functional processes.",
    intent: "Create process models using activity diagrams and swim-lane diagrams to visualize workflows, identify cross-functional handoffs, and derive functional requirements from process flows.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Visualizing cross-functional workflows that span multiple roles or departments", "Identifying handoffs, decision points, and parallel activities in a process", "Deriving functional requirements from process flow analysis"],
    scenarios: ["The chemical intake process involves the technician, safety officer, and lab manager -- I need to see the full flow", "I need to find gaps in a business process before writing requirements", "Stakeholders disagree on how the current process works -- I need a visual model to align them"],
    estimatedTime: "30-60 min per process model",
    path: "skills/process-modeling/SKILL.md"
  },
  {
    id: "prototyping-strategy",
    name: "Prototyping Strategy",
    description: "Select the right prototyping approach based on risks, uncertainty, and evaluation needs.",
    intent: "Guide requirements engineers in selecting the most effective prototyping approach by asking adaptive questions about the purpose of the prototype, desired fidelity level, lifecycle intent, and evaluation method.",
    type: "interactive",
    phase: "Validation",
    bestFor: ["Choosing the right fidelity and scope for a prototype", "Reducing risk when requirements are uncertain or stakeholders disagree", "Planning prototype evaluation to maximize learning"],
    scenarios: ["Users cannot articulate what they need and we need something concrete to show them", "There is technical uncertainty about whether a feature is feasible", "Stakeholders disagree about the UI approach and we need to resolve it quickly"],
    estimatedTime: "15-20 min",
    path: "skills/prototyping-strategy/SKILL.md"
  },
  {
    id: "quality-attribute",
    name: "Quality Attribute",
    description: "Specify NFRs with Planguage notation -- measurable scales, goals, and trade-offs.",
    intent: "Guide requirements engineers through a systematic process for identifying, prioritizing, and specifying quality attributes (non-functional requirements). Uses a five-step process from broad taxonomy to precise Planguage specifications.",
    type: "component",
    phase: "Specification",
    bestFor: ["Turning vague NFRs into measurable, testable specifications", "Making explicit trade-offs between competing quality attributes", "Specifying performance, security, availability, and usability targets"],
    scenarios: ["Stakeholders say the system must be 'fast' and 'secure' but I need actual numbers", "Performance and usability are both 'critical' -- I need a framework to resolve the conflict"],
    estimatedTime: "30-60 min",
    path: "skills/quality-attribute/SKILL.md"
  },
  {
    id: "questionnaire-design",
    name: "Questionnaire Design",
    description: "Design requirements questionnaires with effective questions and bias-resistant ordering.",
    intent: "Design and deploy requirements questionnaires that gather structured data from a broad stakeholder audience. Covers when questionnaires work (vs. interviews), open vs. closed question design, scale types, and analysis of results.",
    type: "component",
    phase: "Elicitation",
    bestFor: ["Gathering requirements priorities from a large stakeholder group", "Validating assumptions from interviews with broader data", "Collecting structured preference data for feature prioritization"],
    scenarios: ["I interviewed 5 stakeholders but need to validate priorities with the 200 users across 8 labs", "I need to know which features matter most to different user groups before committing scope", "Stakeholder opinions conflict and I need quantitative data to resolve disagreements"],
    estimatedTime: "2-4 hours to design",
    path: "skills/questionnaire-design/SKILL.md"
  },
  {
    id: "re-process-improvement",
    name: "RE Process Improvement",
    description: "Assess, plan, pilot, and measure improvements to your RE processes.",
    intent: "Guide requirements engineers and process owners through a structured improvement cycle for requirements engineering practices. Orchestrates four phases -- assess current RE practices, plan targeted improvements, create and pilot new process assets, and evaluate results using metrics.",
    type: "workflow",
    phase: "Cross-Cutting",
    bestFor: ["Diagnosing and fixing recurring requirements quality problems", "Maturing an ad hoc RE process into a defined, repeatable practice", "Measuring the effectiveness of requirements engineering activities"],
    scenarios: ["Our last three projects had major requirements defects. We need to fix our RE process.", "We have no standard RE process -- each project does requirements differently", "Management wants metrics to show that our RE process improvement investment is paying off"],
    estimatedTime: "4-8 hours initial assessment",
    path: "skills/re-process-improvement/SKILL.md"
  },
  {
    id: "re-tool-selection",
    name: "RE Tool Selection",
    description: "Select and evaluate requirements engineering tools based on project context.",
    intent: "Guide requirements engineers through selecting appropriate tools for requirements development (RD) and requirements management (RM) based on project size, current tool maturity, key pain points, and integration needs.",
    type: "interactive",
    phase: "Cross-Cutting",
    bestFor: ["Evaluating whether to adopt a dedicated RM tool", "Selecting between competing RE tool options", "Planning a tool migration strategy from spreadsheets to a structured tool"],
    scenarios: ["We are managing requirements in spreadsheets and it is becoming unmanageable. What tool should we use?", "Management wants us to evaluate RM tools. How do I structure the evaluation?", "We bought an RM tool but nobody uses it. How do we fix adoption?"],
    estimatedTime: "15-25 min",
    path: "skills/re-tool-selection/SKILL.md"
  },
  {
    id: "requirements-analysis-process",
    name: "Requirements Analysis Process",
    description: "Transform raw elicitation outputs into analyzed, modeled requirements.",
    intent: "Guide requirements engineers through the analysis process that transforms raw elicitation outputs (notes, transcripts, brainstorms) into structured, analyzed requirements. Orchestrates visual modeling, data analysis, requirement decomposition, and conflict resolution.",
    type: "workflow",
    phase: "Analysis",
    bestFor: ["Transforming raw elicitation notes into structured requirements", "Applying visual models to discover missing requirements", "Decomposing high-level needs into detailed functional requirements"],
    scenarios: ["I have 3 hours of elicitation notes and need to turn them into a requirements specification", "Requirements feel incomplete. I need a systematic approach to find the gaps."],
    estimatedTime: "2-4 hours per feature area",
    path: "skills/requirements-analysis-process/SKILL.md"
  },
  {
    id: "requirements-baselining",
    name: "Requirements Baselining",
    description: "Establish baselines with version control and approval processes.",
    intent: "Guide requirements engineers through establishing formal requirements baselines with proper version labeling, entry criteria, configuration management, and approval processes.",
    type: "component",
    phase: "Management",
    bestFor: ["Establishing a formal reference point after requirements approval", "Setting up version control and labeling conventions for requirements documents", "Defining entry criteria that requirements must meet before baselining"],
    scenarios: ["The SRS has been reviewed and approved -- I need to formally baseline it before development begins", "We are starting Release 2 and need to know exactly what was in the Release 1 baseline", "An auditor asks which version of the requirements was used for the current build"],
    estimatedTime: "30-45 min",
    path: "skills/requirements-baselining/SKILL.md"
  },
  {
    id: "requirements-development-process",
    name: "Requirements Development Process",
    description: "Orchestrate the complete RE development lifecycle from vision through validation.",
    intent: "Guide requirements engineers through the complete requirements development lifecycle -- from establishing the project foundation (vision, stakeholders, scope) through elicitation, analysis, specification, and validation. This is the meta-workflow that orchestrates all four subdisciplines of requirements engineering.",
    type: "workflow",
    phase: "Cross-Cutting",
    bestFor: ["Planning the complete requirements effort for a new project", "Orchestrating multiple RE techniques into a coherent process", "Ensuring no critical requirements activities are skipped"],
    scenarios: ["I am starting a new project and need to plan the entire requirements development effort", "Our requirements process is ad-hoc and we keep missing steps -- I need a structured approach", "I need to estimate how long the requirements phase will take for different project sizes"],
    estimatedTime: "2-16 weeks depending on project size",
    path: "skills/requirements-development-process/SKILL.md"
  },
  {
    id: "requirements-elicitation-workshop",
    name: "Requirements Elicitation Workshop",
    description: "Plan and execute structured elicitation sessions using multiple techniques.",
    intent: "Guide requirements engineers through planning and executing a complete elicitation session -- from preparation through facilitation to post-session synthesis. Orchestrates elicitation techniques into a structured session plan.",
    type: "workflow",
    phase: "Elicitation",
    bestFor: ["Planning a structured elicitation session for a new project", "Running an effective requirements workshop with multiple stakeholders", "Synthesizing elicitation outputs into actionable requirements"],
    scenarios: ["I have a 3-hour window with 5 stakeholders. Help me plan the session.", "We keep getting incomplete requirements from interviews. I need a better process."],
    estimatedTime: "30-45 min planning; 2-4 hours execution",
    path: "skills/requirements-elicitation-workshop/SKILL.md"
  },
  {
    id: "requirements-management-process",
    name: "Requirements Management Process",
    description: "Establish baselines, version control, attribute tracking, and status monitoring.",
    intent: "Guide requirements engineers through establishing and maintaining the requirements management infrastructure -- baselining, version control, requirement attributes, status tracking, and requirements burndown.",
    type: "workflow",
    phase: "Management",
    bestFor: ["Setting up requirements management infrastructure for a project", "Tracking requirements status and progress through development", "Maintaining requirement attributes, versions, and baselines"],
    scenarios: ["I need to set up a requirements management process for a new project", "We have 200 requirements and no way to track which are implemented and verified"],
    estimatedTime: "2-4 hours initial setup",
    path: "skills/requirements-management-process/SKILL.md"
  },
  {
    id: "requirements-reuse",
    name: "Requirements Reuse",
    description: "Reuse requirements across projects using patterns, catalogs, and product-line strategies.",
    intent: "Guide requirements engineers in identifying reuse opportunities, selecting appropriate reuse mechanisms (copy, reference, adapt), and building a sustainable requirements reuse repository.",
    type: "component",
    phase: "Cross-Cutting",
    bestFor: ["Leveraging requirements from past projects for a new similar system", "Building a reusable requirements catalog for a product line", "Identifying requirement patterns that apply across domains"],
    scenarios: ["We are building a second lab management system and want to reuse requirements from the first", "Our organization builds similar systems repeatedly but starts from scratch every time", "I need standard requirement patterns for common features like authentication or audit logging"],
    estimatedTime: "20-40 min",
    path: "skills/requirements-reuse/SKILL.md"
  },
  {
    id: "requirements-review-advisor",
    name: "Requirements Review Advisor",
    description: "Choose and plan review approaches from walkthroughs to Fagan inspections.",
    intent: "Guide requirements engineers in selecting the right review approach (informal review, walkthrough, or formal inspection) and planning the review process. Covers the Fagan inspection method with its six stages.",
    type: "interactive",
    phase: "Validation",
    bestFor: ["Selecting the right review formality level for a project", "Planning and conducting formal requirements inspections", "Creating defect checklists tailored to your requirements"],
    scenarios: ["Requirements are drafted and I need to plan the review. What process should I use?", "We have a safety-critical system. How should we inspect the requirements?", "Our reviews never find real issues -- how do I make them more effective?"],
    estimatedTime: "10-15 min",
    path: "skills/requirements-review-advisor/SKILL.md"
  },
  {
    id: "requirements-risk-assessment",
    name: "Requirements Risk Assessment",
    description: "Identify and mitigate risks specific to requirements engineering.",
    intent: "Guide requirements engineers through identifying, analyzing, and mitigating risks that originate from requirements activities -- elicitation gaps, specification ambiguity, unstable requirements, inadequate validation, and poor change management.",
    type: "component",
    phase: "Cross-Cutting",
    bestFor: ["Identifying risks arising from requirements elicitation and analysis gaps", "Prioritizing requirements risks using exposure-based analysis", "Creating mitigation strategies for specification and validation risks"],
    scenarios: ["Our last project failed because of missed requirements -- how do I prevent that?", "Stakeholders keep changing requirements and I need to quantify the risk to the project", "I need a risk register focused on requirements engineering activities"],
    estimatedTime: "15-30 min",
    path: "skills/requirements-risk-assessment/SKILL.md"
  },
  {
    id: "requirements-status-tracking",
    name: "Requirements Status Tracking",
    description: "Track requirements through their lifecycle from Proposed to Verified.",
    intent: "Guide requirements engineers through establishing and maintaining a requirements status tracking system with defined lifecycle states, transition rules, status distribution visualization, and progress reporting.",
    type: "component",
    phase: "Management",
    bestFor: ["Providing visibility into requirements progress across the lifecycle", "Identifying bottlenecks where requirements are stalling", "Generating progress reports for management and stakeholders"],
    scenarios: ["The project manager asks: how many requirements are implemented and verified?", "I suspect some requirements are stuck in 'Drafted' status -- I need to find them", "We need a dashboard showing requirements progress for the steering committee"],
    estimatedTime: "20-30 min setup",
    path: "skills/requirements-status-tracking/SKILL.md"
  },
  {
    id: "requirements-testing",
    name: "Requirements Testing",
    description: "Derive test cases from requirements to verify testability and plan acceptance testing.",
    intent: "Derive test cases directly from requirements documents before any code is written. Use this to verify that every requirement is testable, to expose ambiguous or incomplete requirements through the discipline of writing concrete test steps.",
    type: "component",
    phase: "Validation",
    bestFor: ["Verifying that requirements are testable before development begins", "Deriving acceptance test cases from use cases and functional requirements", "Exposing ambiguous or incomplete requirements through test case writing"],
    scenarios: ["I need to verify requirements are complete and testable before handing them to developers", "The QA team wants to start acceptance test planning but development has not begun", "Requirements contain vague terms like 'fast' and 'user-friendly' that need fit criteria"],
    estimatedTime: "30-60 min per requirement group",
    path: "skills/requirements-testing/SKILL.md"
  },
  {
    id: "requirements-traceability",
    name: "Requirements Traceability",
    description: "Build traceability matrices linking objectives, requirements, design, and tests.",
    intent: "Create a traceability matrix that establishes bidirectional links between business objectives, requirements, design elements, and test cases.",
    type: "component",
    phase: "Management",
    bestFor: ["Demonstrating that all business needs are covered by requirements", "Performing change impact analysis across the requirements chain", "Satisfying regulatory audit requirements for traceability"],
    scenarios: ["A stakeholder wants to change a business objective -- I need to know which requirements are affected", "I need to prove to an auditor that every requirement has a corresponding test case"],
    estimatedTime: "60-90 min initial setup",
    path: "skills/requirements-traceability/SKILL.md"
  },
  {
    id: "requirements-validation-process",
    name: "Requirements Validation Process",
    description: "Validate requirements through reviews, inspections, prototyping, and conceptual testing.",
    intent: "Guide requirements engineers through the complete validation process that verifies requirements are correct, complete, feasible, and unambiguous before they are baselined. Orchestrates formal inspections, prototype-based validation, conceptual testing, and acceptance criteria verification.",
    type: "workflow",
    phase: "Validation",
    bestFor: ["Conducting a thorough requirements review before baseline", "Combining multiple validation techniques into a complete process", "Finding defects in requirements before development begins"],
    scenarios: ["The SRS is drafted and I need to validate it before the team starts building", "We keep finding requirements defects during testing. How do I catch them earlier?"],
    estimatedTime: "4-8 hours for full validation",
    path: "skills/requirements-validation-process/SKILL.md"
  },
  {
    id: "specification-review-checklist",
    name: "Specification Review Checklist",
    description: "Review requirements and SRS documents using structured quality checklists.",
    intent: "Provide structured checklists for reviewing both individual requirements and complete SRS documents. Covers the 10 characteristics of well-written individual requirements and the 8 characteristics of a well-written SRS, with a defect taxonomy.",
    type: "component",
    phase: "Validation",
    bestFor: ["Conducting formal or informal requirements inspections", "Evaluating quality of individual requirements statements", "Assessing completeness and consistency of an SRS document"],
    scenarios: ["I need to review an SRS before baselining and want a structured checklist", "Requirements keep coming back from developers with questions about ambiguity", "We want to establish a quality gate for requirements before they enter development"],
    estimatedTime: "15-30 min per review session",
    path: "skills/specification-review-checklist/SKILL.md"
  },
  {
    id: "srs-document",
    name: "SRS Document",
    description: "Build a Software Requirements Specification with EARS templates and labeling.",
    intent: "Guide requirements engineers through creating a complete Software Requirements Specification (SRS) document that organizes functional requirements by system feature, documents data requirements, external interfaces, quality attributes, and constraints.",
    type: "component",
    phase: "Specification",
    bestFor: ["Creating a formal requirements baseline for a project", "Organizing requirements for regulatory or contractual compliance", "Structuring requirements for large systems with multiple subsystems"],
    scenarios: ["My client requires a formal SRS before approving the design phase", "I need to organize 200+ requirements into a coherent, reviewable document"],
    estimatedTime: "4-8 hours full document",
    path: "skills/srs-document/SKILL.md"
  },
  {
    id: "stakeholder-analysis",
    name: "Stakeholder Analysis",
    description: "Identify and classify stakeholders, user classes, and their influence.",
    intent: "Systematically identify all stakeholders and user classes for a software project, classify them by type and influence, and establish appropriate engagement strategies.",
    type: "component",
    phase: "Foundation",
    bestFor: ["Identifying all stakeholders before elicitation begins", "Classifying user classes to prioritize conflicting needs", "Establishing product champion roles for each user class"],
    scenarios: ["I'm starting a new project and need to know who to interview for requirements", "Two user groups want conflicting features -- I need to understand their relative priority"],
    estimatedTime: "30-60 min",
    path: "skills/stakeholder-analysis/SKILL.md"
  },
  {
    id: "state-modeling",
    name: "State Modeling",
    description: "Create state-transition diagrams and state tables for object lifecycle behavior.",
    intent: "Model the lifecycle of domain objects using state-transition diagrams and state tables. Use this when requirements involve objects that move through defined states in response to events, and where invalid transitions must be prevented.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Modeling object lifecycles with defined state transitions", "Discovering missing requirements for event-state combinations", "Specifying valid and invalid state transitions"],
    scenarios: ["An order goes through multiple statuses and I need to specify all valid transitions and what triggers them", "I need to find missing exception handling requirements for a chemical record lifecycle"],
    estimatedTime: "30-60 min per object",
    path: "skills/state-modeling/SKILL.md"
  },
  {
    id: "use-case",
    name: "Use Case",
    description: "Write structured use case specifications with triggers, flows, and exceptions.",
    intent: "Create detailed use case specifications that capture how users interact with a system to achieve specific goals. Each use case documents the actor, preconditions, trigger, normal flow, alternative flows, exceptions, and postconditions.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Documenting complex user-system interactions with multiple paths", "Capturing exception handling and error scenarios systematically", "Specifying behavior for regulated or safety-critical systems"],
    scenarios: ["I need to specify how a pharmacist processes a prescription with all the validation steps and error cases", "The user story is too simple to capture the branching logic -- I need a full use case"],
    estimatedTime: "15-30 min per use case",
    path: "skills/use-case/SKILL.md"
  },
  {
    id: "user-story-re",
    name: "User Story (RE)",
    description: "Write requirements-focused user stories with INVEST criteria and acceptance criteria.",
    intent: "Create user stories that satisfy requirements engineering standards -- not just agile placeholders for conversation, but traceable, testable, prioritized expressions of user need.",
    type: "component",
    phase: "Analysis",
    bestFor: ["Writing user stories that meet RE quality standards", "Adding acceptance criteria that are testable and traceable", "Evaluating stories against INVEST criteria before sprint planning"],
    scenarios: ["I need user stories for an agile project that also need to satisfy regulatory traceability", "My team writes vague user stories. I need a quality standard."],
    estimatedTime: "5-15 min per story",
    path: "skills/user-story-re/SKILL.md"
  },
  {
    id: "value-cost-risk-analysis",
    name: "Value/Cost/Risk Analysis",
    description: "Prioritize requirements using a multi-factor value/cost/risk scoring model.",
    intent: "Guide requirements engineers through the Wiegers value/cost/risk priority model to produce a defensible, quantitative prioritization of requirements. Uses relative benefit and penalty scoring, cost and risk estimation, and a priority formula.",
    type: "component",
    phase: "Prioritization",
    bestFor: ["Resolving stakeholder disagreements about requirement priority", "Producing a defensible, quantitative basis for release planning", "Balancing business value against implementation cost and technical risk"],
    scenarios: ["Three stakeholder groups each insist their features are highest priority -- I need an objective framework", "We have 40 requirements but can only deliver 20 in Release 1 -- how do we choose?", "Management wants a data-driven justification for what we included and excluded"],
    estimatedTime: "45-90 min",
    path: "skills/value-cost-risk-analysis/SKILL.md"
  },
  {
    id: "vision-and-scope",
    name: "Vision & Scope",
    description: "Create a vision and scope document with business objectives and scope boundaries.",
    intent: "Guide requirements engineers through building a vision and scope document that defines business requirements (objectives, success metrics, risk), project scope (features, limitations, exclusions), and business context (stakeholder profiles, priorities, deployment).",
    type: "component",
    phase: "Foundation",
    bestFor: ["Defining project objectives and measurable success criteria", "Establishing scope boundaries before elicitation begins", "Aligning stakeholders on what is in and out of scope"],
    scenarios: ["I'm starting a new project and need to document the business requirements and scope before elicitation", "Stakeholders disagree on what the product should do -- I need a vision and scope document to align them"],
    estimatedTime: "60-90 min",
    path: "skills/vision-and-scope/SKILL.md"
  },
  {
    id: "writing-requirements",
    name: "Writing Requirements",
    description: "Write clear, testable requirements using EARS templates and quality checklists.",
    intent: "Write excellent individual requirements using proven sentence patterns (EARS templates), shall/should/will conventions, and a quality self-check against the ten characteristics of excellent requirements.",
    type: "component",
    phase: "Specification",
    bestFor: ["Drafting clear, testable functional requirements from scratch", "Improving vague or ambiguous existing requirements", "Applying EARS sentence patterns to standardize requirement language"],
    scenarios: ["I have a feature idea but need to turn it into a proper shall-statement", "Reviewers flagged my requirements as vague or untestable -- I need to rewrite them", "I want a checklist to verify my requirements meet quality standards before review"],
    estimatedTime: "5-15 min per requirement",
    path: "skills/writing-requirements/SKILL.md"
  }
];

const COMMANDS = [
  {
    id: "develop-requirements",
    name: "/develop-requirements",
    description: "Run the complete requirements development lifecycle from vision through validated, baselined requirements.",
    argumentHint: "<project, product, or system name and context>",
    uses: ["requirements-development-process", "vision-and-scope", "stakeholder-analysis", "context-diagram", "elicitation-technique-selector", "srs-document", "requirements-validation-process"],
    outputs: ["Vision and scope document", "Stakeholder register", "Baselined SRS with validated requirements"],
    path: "commands/develop-requirements.md"
  },
  {
    id: "manage-requirements",
    name: "/manage-requirements",
    description: "Set up and run requirements management for baselined requirements.",
    argumentHint: "<project name and baseline context>",
    uses: ["requirements-management-process", "requirements-baselining", "change-control-process", "change-impact-analysis", "requirements-traceability", "requirements-status-tracking"],
    outputs: ["Baselined requirements with version control", "Change control board charter and process", "Traceability matrix", "Status tracking dashboard"],
    path: "commands/manage-requirements.md"
  },
  {
    id: "elicit",
    name: "/elicit",
    description: "Plan and execute requirements elicitation with technique selection.",
    argumentHint: "<stakeholder group, feature area, or elicitation goal>",
    uses: ["elicitation-technique-selector", "elicitation-interview", "observation-analysis", "questionnaire-design", "requirements-elicitation-workshop"],
    outputs: ["Elicitation strategy with technique selection rationale", "Prepared session guides", "Captured requirements and findings"],
    path: "commands/elicit.md"
  },
  {
    id: "write-srs",
    name: "/write-srs",
    description: "Create a structured SRS document with data dictionary and acceptance criteria.",
    argumentHint: "<project or feature area to specify>",
    uses: ["srs-document", "writing-requirements", "data-dictionary", "acceptance-criteria", "specification-review-checklist"],
    outputs: ["Structured SRS document", "Data dictionary", "Acceptance criteria", "Self-review results"],
    path: "commands/write-srs.md"
  },
  {
    id: "analyze",
    name: "/analyze",
    description: "Model and refine requirements using appropriate analysis techniques.",
    argumentHint: "<feature area or domain to model>",
    uses: ["analysis-advisor", "use-case", "user-story-re", "process-modeling", "data-modeling", "state-modeling", "decision-table", "dialog-map", "quality-attribute"],
    outputs: ["Selected modeling techniques with rationale", "Analysis models", "Quality attribute specifications"],
    path: "commands/analyze.md"
  },
  {
    id: "validate",
    name: "/validate",
    description: "Review and validate requirements before baselining.",
    argumentHint: "<SRS or requirements set to validate>",
    uses: ["requirements-review-advisor", "requirements-validation-process", "requirements-testing", "prototyping-strategy", "specification-review-checklist"],
    outputs: ["Validation plan", "Defect log", "Validation report"],
    path: "commands/validate.md"
  },
  {
    id: "prioritize",
    name: "/prioritize",
    description: "Select the right prioritization method and rank requirements.",
    argumentHint: "<requirements set, constraints, and decision context>",
    uses: ["prioritization-advisor-re", "moscow-prioritization", "value-cost-risk-analysis"],
    outputs: ["Prioritization method selection", "Ranked requirements", "Release allocation plan"],
    path: "commands/prioritize.md"
  },
  {
    id: "agile-re",
    name: "/agile-re",
    description: "Run requirements engineering in an agile context.",
    argumentHint: "<product or feature area for agile RE>",
    uses: ["agile-requirements-process", "vision-and-scope", "user-story-re", "acceptance-criteria", "requirements-validation-process"],
    outputs: ["Lightweight vision and scope", "Seeded product backlog", "Sprint-ready requirements"],
    path: "commands/agile-re.md"
  },
  {
    id: "analyze-change",
    name: "/analyze-change",
    description: "Process a requirements change request through impact analysis.",
    argumentHint: "<change request description and context>",
    uses: ["change-control-process", "change-impact-analysis", "requirements-traceability"],
    outputs: ["Classified change request", "Impact analysis with effort estimate", "CCB decision recommendation"],
    path: "commands/analyze-change.md"
  }
];
